---
title: "First Knit"
author: "Elizabeth Rivera"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct punctuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare English class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I previously attended Loara High School in, Anaheim, California. I graduated from Loara in 2014. I've always found English class more challenging than math throughout all my school years. Math has always been a fun/ stress free subject where I did best in.

     


## Your computer and your and its capability?  
For this class,  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
For this class, I have access to a Lenovo laptop to use both at school and at home. On a scale of 1 to 10, I would rate myself a 6 on computer "skills" because I can navigate through a laptop without much guidance but am far from a professional. I enjoy to learn new things and so I look forward in learning something new during each lecture. Also, I have access to internet at home and work without any connection difficulties. 
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
My name is Elizabeth and the name itself has many variations. Personally, I don't have a preference. Family, friends, co-workers call me: Elizabeth, Liz, Lisa, Eli, and Lizzy to name a few.
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
In life I want to achieve helping others. Many consider this a simple achievement without much depth. This simple achievement/aspiration can change a person's entire life, which is why I don't consider it to be a simple task. Unrelated, the college subject that interests me the most is math. I've taken Calculus, physics, you name it except for Statistics. I am trying to apply for the RN program and one day become a physician for women's health.
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
I've never had the opportunity to travel to a foreign country. If given the opportunity I would love to visit Australia, Cuba, Greece, and Canada. I've never been in the military but if drafted I would love the Air Force. The idea of flying gives me a sense of tranquility in a world of chaos.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
I'm currently taking Math 115 and have never taken a Statistics course before. I didn't know Math 115 only satisfies a general education requirement. Knowing this now, I think I might need to take Math 116 in the future.
I need to attain an A in Math 115 to not upset my future plans but also for personal achievement. My plan is to get accepted into the RN program and practice in Orange County (hometown) to continue my education and one day be a physician for women's health. 
   
 






  




